### ISSUE TITLE
ScratchImage.Compress refusing to work on B8G8R8A8_UNORM 

### ISSUE THREAD

**Issue by Kfestofil** [deng0/DirectXTexNet#14]
I do not know basically anything about Texture compression or anything like that, but I am trying to fix some code that is not even mine, and it keeps crashind on onse specific line:

`ddsimage = resizedimage.Compress(GetDXGIFormat(resourcePCT.TextureFormat), TEX_COMPRESS_FLAGS.PARALLEL, 0.5f);`

where resizedimage is of type DirectXTexNet.ActualScratchImageImpl, and the GetDXGIFormat returns DXGI_FORMAT.B8G8R8A8_UNORM

The error mmessage is the following:

```
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at DirectXTexNet.ScratchImageImpl.Compress(DXGI_FORMAT format, TEX_COMPRESS_FLAGS compress, Single threshold)
   at texmipper.TexMipper.ConvertToPCT(ResourcePct resourcePCT, String inputtexturefilepath) in D:\modding garbage\Texmipper project\texmipper\TexMipper.cs:line 177
   at texmipper.TexMipper.Main(String[] args) in D:\modding garbage\Texmipper project\texmipper\TexMipper.cs:line 71
```

**Comment by deng0** [comment]
You need to specify the desired compressed texture format (BC) when calling Compress().
DXGI_FORMAT.B8G8R8A8_UNORM is not a compressed format.

As this library is just a slim wrapper for the DirectXTex library, it's best to consult the DirectXTex documentation:
https://github.com/microsoft/DirectXTex/wiki/Compress

**Comment by Kfestofil** [comment]
Thanks! Got it all figured out now!
